apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.radarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "radarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.radarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "radarr.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.radarr.podSecurityContext | nindent 8 }}
      dnsPolicy: "None"
      dnsConfig:
        nameservers: {{- .Values.global.nameservers | toYaml | nindent 10 }}
      containers:
        - name: radarr
          securityContext:
            {{- toYaml .Values.radarr.securityContext | nindent 12 }}
          image: "{{ .Values.radarr.image.repository }}:{{ .Values.radarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.radarr.image.pullPolicy }}
          env:
          - name: TZ
            value: {{ .Values.global.timezone | squote }}
          - name: PUID
            value: {{ .Values.global.user.uid | squote }}
          - name: PGID
            value: {{ .Values.global.user.gid | squote }}
          {{- with .Values.radarr.extraEnv }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.radarr.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.radarr.resources | nindent 12 }}
          volumeMounts:
          - name: medias
            mountPath: /tv
            subPath: {{ .Values.mediaPVC.paths.tv }}
          - name: medias
            mountPath: /downloads
            subPath: {{ .Values.mediaPVC.paths.downloads }}
          {{- if .Values.radarr.persistence.enabled }}
          - name: {{ include "radarr.fullname" . | printf "config-%s" }}
            mountPath: /config
          {{- end }}
          {{- with .Values.radarr.extraVolumeMounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
      volumes:
        - name: medias
          persistentVolumeClaim:
            claimName: {{ .Values.mediaPVC.name }}
      {{- with .Values.radarr.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.radarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if .Values.radarr.persistence.enabled }}
    - metadata:
        name: {{ include "radarr.fullname" . | printf "config-%s" }}
      spec:
        storageClassName: {{ .Values.radarr.persistence.storageClassName }}
        accessModes: {{- .Values.radarr.persistence.accessModes | toYaml | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.radarr.persistence.size }}
    {{- end }}
