apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: kubernetes
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: "kubernetes"
    localASN: 64512
    peers:
    - name: {{ .Values.peer.name }}
      peerASN: 64512
      peerAddress: {{ .Values.peer.address | squote }}
      peerConfigRef:
        name: {{ .Values.peer.name }}
