apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        kubernetesAuthCredentials:
          identityId: {{- .Values.identityId | toYaml | nindent 12 }}
      secretsScope:
        projectSlug: {{ .Values.projectSlug }}
        environmentSlug: prod
        secretsPath: {{ .Values.secretsPath }}
      hostAPI: {{ .Values.hostAPI }}
