global:
  timezone: 'Europe/Paris'
  user:
    uid: 1000
    gid: 1000
  
  nameservers:
    - 1.1.1.1
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    domain: chart-example.local
    backends:
      transmission:
        enabled: false
      prowlarr:
        enabled: false
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

mediaPVC:
  name: media
  accessModes:
    - ReadWriteMany
  size: 2000Gi
  
transmission:
  image:
    repository: haugene/transmission-openvpn
    pullPolicy: IfNotPresent
    tag: ""
  
  imagePullSecrets: []
  
  provider:
    name: custom
    endpoint: Netherlands
    protocol: udp
    localNetwork: '192.168.0.0/24'
    user: {}
      # name:
      # password:
      # or
      # extraSecret:
      #   name:
      #   userKey:
      #   passwordKey:
      # or
      # externalSecret:
      #   secretStoreRef:
      #     kind:
      #     name:
      #   secret:
      #     userKey:
      #     passKey:
      
    customOVPN: {}
  
  firewall:
    enable: false
    allowGatewayNetwork: false
    extraPorts: ''
    disableReject: false
  
  rpc:
    enabled: false
    auth_required: false
    user:
      name: default
      password: default
      # can also be
      # extraSecret:
      #   name:
      #   userKey:
      #   passwordKey:
      # or
      # externalSecret:
      #   secretStoreRef:
      #     kind:
      #     name:
      #   secret:
      #     userKey:
      #     passKey:
    whitelist: []
  
  persistence:
    config:
      enabled: false
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 10Mi
    downloads:
      enabled: false
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 100Gi
  
  extraEnv: {}
  
  extraVolumes: {}
  extraVolumeMounts: {}
  
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  
  podAnnotations: {}
  podSecurityContext: {}
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  
  service:
    type: ClusterIP
    port: 9091
  
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 2.1.5
  imagePullSecrets: []

  persistence:
    enabled: false
    accessModes: RWO
    size: 128Mi

  service:
    type: ClusterIP
    port: 9696
  
  extraEnv: {}
  extraVolumes: {}
  extraVolumeMounts: {}
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  
