app:
  name: external-secret-operator
  project: infra
  source:
    repoURL: git@github.com:external-secrets/external-secrets.git
    targetRevision: v0.20.4
    path: deploy/charts/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secret-operator
  helm:
    values: ''
