app:
  name: infisical-secret-store
  project: infra
  source:
    repoURL: git@github.com:pale-whale/infra.git
    targetRevision: HEAD
    path: k8s/charts/infisical-secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  helm:
    values: |
      eso_account:
        name: external-secret-operator-external-secrets
        namespace: external-secret-operator
      identityId:
        name: infisical-identity
        namespace: external-secret-operator
        key: id
      projectSlug: homelab-secrets-c-nj-c
      secretsPath: /
      hostAPI: 'http://infisical-infisical-standalone-infisical.infisical:8080'
