{{- if .Values.transmission.rpc.user.externalSecret }}
{{- with .Values.transmission.rpc.user.externalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "transmission-openvpn.fullname" $ | printf "rpc-credentials-%s" }}
spec:
  secretStoreRef: {{- .secretStoreRef | toYaml | nindent 4 }}
  target:
    name: {{ include "transmission-openvpn.fullname" $ | printf "rpc-credentials-%s" }}
  data:
    - secretKey: user
      remoteRef:
        key: {{ .secret.userKey }}
    - secretKey: password
      remoteRef:
        key: {{ .secret.passKey }}
{{- end }}
{{- end }}
