{{- if .Values.transmission.provider.customOVPN -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $filename, $config := .Values.transmission.provider.customOVPN }}
{{- printf "%s: |" $filename | nindent 2 }}
{{- $config | b64enc | nindent 4}}
{{- end }}
{{- end }}
