{{- if .Values.transmission.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transmission-openvpn.serviceAccountName" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
  {{- with .Values.transmission.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
