{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.ingress.tls }}
  tls:
    {{- range .Values.global.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.ingress.backends.transmission.enabled }}
    - host: {{ .Values.global.ingress.backends.transmission.host | default .Values.global.ingress.domain }}
      http:
        paths: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: http
            port:
              number: {{ .Values.transmission.service.port }}
    {{- end }}
    {{- if .Values.global.ingress.backends.prowlarr.enabled }}
    - host: {{ .Values.global.ingress.backends.prowlarr.host | default .Values.global.ingress.domain }}
      http:
        paths: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: http
            port:
              number: {{ .Values.prowlarr.service.port }}
    {{- end }}
{{- end }}
