apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mediaPVC.name }}
spec:
  {{- with .Values.mediaPVC.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes: {{ .Values.mediaPVC.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.mediaPVC.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.transcodePVC.name }}
spec:
  {{- with .Values.transcodePVC.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes: {{ .Values.transcodePVC.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.transcodePVC.size }}
