apiVersion: v2
name: keycloak
description: deploy keycloak

type: application

appVersion: 26.4.4
version: 0.0.1

dependencies:
  - name: cluster
    alias: database
    condition: database.enabled
    version: v0.3.1
    repository: https://cloudnative-pg.github.io/charts
