{{- if and .Values.ygege.enable .Values.ygege.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ygege.serviceAccountName" . }}
  labels:
    {{- include "ygege.labels" . | nindent 4 }}
  {{- with .Values.ygege.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
