{{- if .Values.ygege.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ygege.fullname" . }}
  labels:
    {{- include "ygege.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ygege.service.type }}
  ports:
    - port: {{ .Values.ygege.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ygege.selectorLabels" . | nindent 4 }}
{{- end }}
